import { ISentence } from '~/core/interfaces/Sentence';

export const MiquelSentences: ISentence = {
    startVerbs: [
        'bent',
        'klinkt',
        'praat',
        'loopt',
        'codeert',
        'typt',
        'ademt',
        'kauwt',
        'spuugt',
        'zingt',
        'schaatst',
        'vecht',
        'sport',
        'schreeuwt',
        'zeikt',
        'kookt',
        'vliegt',
        'lijkt',
        'denkt',
    ],
    endVerbs: [
        'vangt',
        'ruikt',
        'eet',
        'hoort',
        'ziet',
        'temt',
        'ontdekt',
        'slacht',
        'onderzoekt',
        'aait',
        'koopt',
        'verkoopt',
        'water geeft',
        'in elkaar slaat',
        'melkt',
        'kiest',
        'scheert',
        'tekent',
        'steelt',
        'zoekt',
        'kent',
        'bezit',
    ],
    adverbs: [
        'jong',
        'cool',
        'goed',
        'grappig',
        'vreemd',
        'Smart',
        'saai',
        'smakelijk',
        'aantrekkelijk',
        'zelfverzekerd',
        'genderneutraal',
        'hongerig',
        'gemeen',
        'passief agressief',
        'eerlijk',
        'betrouwbaar',
        'vreemd',
        'grappig',
        'gevaarlijk',
        'slim',
        'kalm',
        'luid',
        'pessimistisch',
        'optimistisch',
        'zakelijk',
    ],
    nouns: [
        'vis',
        'wasbeer',
        'mol',
        'kameel',
        'sneeuwpop',
        'kat',
        'dromedaris',
        'hond',
        'leeuw',
        'kamerplant',
        'vegatariër',
        'dinosaurus',
        'slang',
        'koe',
        'olifant',
        'kabouter',
        'hulpverlener',
        'auto',
        'meeuw',
        'zakenman',
        'gladde paling',
        'uil',
        'stagiair',
    ],
}