import IName from '~/core/interfaces/Name';

export const NickNames: IName = {
    firstName: {
        firstHalf: [
            'Ni',
            'Nie',
            'Ny',
            'Nai',
            'Nei',
            'Nij',
            'No',
            'Nee',
            'Nu',
            'Na',
        ],
        secondHalf: [
            'k',
            'kc',
            'ck',
            'cc',
            'lk',
            'cky',
            'kkie',
            'cht',
            'ke',
            'ks',
        ],
        single: [
            'Niko',
            'Nickelodeon',
            'Neus',
            'Naald',
            'Neef',
            'Niffo',
            'Nike',
            'Xiaomi',
            'Naaltie',
        ]
    },
    lastName: {
        firstHalf: [
            'Huig',
            'Hauch',
            'Huyg',
            'Haar',
            'Heeg',
            'Snuif',
            'Kuif',
            'Zuig',
            'Zuijg',
            'Buig',
            'Pluim',
            'Pruim',
            'Huts',
        ],
        secondHalf: [
            'en',
            'on',
            'an',
            'aen',
            'uil',
            'ken',
            'on',
            'ben',
            'ren',
            'Smart',
            'cringe',
            'nuts',
            'men',
            'man',
            'blik',
            'gel',
            'ie',
            'neef',
            'sus',
            'bal',
            'nat',
            'stein',
            'poot',
            'noot',
        ],
    },
}